relativeURLs = true
title = "Geoffrey Schnorr"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "PhD Candidate, Economics, Univeristy of California-Davis"
    logo = "headshot_ucd.jpg" 
