relativeURLs = true
title = "Geoffrey C. Schnorr"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "PhD Candidate, UC-Davis"
    logo = "headshot_ucd.jpg"
